### PR TITLE
Moath/at 84/cleanup

### PR DESCRIPTION
**Pull request by mfalthaw**
Cleanup
  - `/src/view/pages/Farmer/tabs/Info/*`

### CODE REVIEW

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 1]
```diff
@@ -1,48 +1,34 @@
...
-  add: 'add',
   edit: 'edit',
   view: 'view',
 };
 
 /**
  * Container for application
  */
-class FarmerInformation extends React.Component<OwnProps, OwnState> {
+class FarmerInformation extends React.Component<{}, OwnStateType> {
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: Please keep the PropsType just to make it more maintainable, as this is a page component and may well be receiving injected props in the future (such as from a fab button). In addition, James will be hooking this up to Redux, so maybe define the whole template Bea sent in `developer`

```
interface OwnPropsType {
}

interface DispatchPropsType {
}

interface StorePropsType {
}

type PropsType = OwnPropsType & DispatchPropsType & StorePropsType;

interface OwnStateType {
}
```

Comment (Right2Drive) [reply src/view/pages/Farmer/tabs/Info/index.tsx]: Also please rename to match the naming scheme used by Bea for her tabs

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 2]
```diff
@@ -1,48 +1,34 @@
...
 
   private initialProps: any;
 
   public static defaultProps = {
     mode: 'view',
   };
 
-  constructor(props: OwnProps) {
+  constructor(props: any) {
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: Change to OwnPropsType

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 3]
```diff
@@ -1,48 +1,34 @@
...
     super(props);
     this.state = { 
       mode: 'view',
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: Maybe it would be a good idea to create a `export type PageMode = 'view' | 'edit'` so the other pages can access this type as I mentioned earlier in the review

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 4]
```diff
@@ -66,22 +51,12 @@ class FarmerInformation extends React.Component<OwnProps, OwnState> {
     this.setState(() => ({ mode: newMode }));
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: Please use the function argument for setState ie: `this.setState(state => ({ mode: newMode }))`

I realize it makes no difference in this situation, but this is a pretty tricky bug to track down when you actually are accessing state, and the people coming after us will be reflecting our style and will not likely know the gotcha's of the framework

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 5]
```diff
@@ -56,7 +42,6 @@ class FarmerInformation extends React.Component<OwnProps, OwnState> {
       farmerNotes: 'Doctor from village A',
       selectedPaymentCycle: 'Weekly',
       selectedPaymentMethod: 'Mobile',
-      // modeHandler:
     };
 
     this.changeMode.bind(this);
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: We decided to make binding optional, so if you prefer to use arrow functions go ahead. I don't imagine I will be writing integration tests anyways so I don't think it will make a difference in the long run, and might be more consistent for you. Just be sure you understand the implications of using an arrow function (just as you should understand the implications of `function name() {}`, `{ name() {} }` and any other function notations). There are fewer gotcha's to be aware of using arrow function, so it might well be better for you guys to use them

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 6]
```diff
@@ -66,22 +51,12 @@ class FarmerInformation extends React.Component<OwnProps, OwnState> {
...
    * Render method for Farmer Information
    */
   public render() {
     if (this.state.mode === modes.view) {
       return <ViewFarmer {...this.initialProps} modeHandler={this.changeMode} />;
-    } else if (this.state.mode === modes.add) {
-      return <AddFarmer {...this.initialProps} modeHandler={this.changeMode} updatePaymentCycle={this.updatePaymentCycle} updatePaymentMethod={this.updatePaymentMethod} />;
     } else if (this.state.mode === modes.edit) {
       return <EditFarmer {...this.initialProps} modeHandler={this.changeMode} />;
     }
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: Please include a default case that throws an exception, just in case someone does break types we don't want to render an empty page with no error

File: src/view/pages/Farmer/tabs/Info/viewFarmer.tsx [hunk 7]
```diff
@@ -20,8 +19,11 @@ interface OwnProps {
 /**
  * Stateless component for viewing farmer information
  */
-const ViewFarmer = (props: OwnProps) => {
+const ViewFarmer = (props: OwnPropsType) => {
 
+  /**
+   * Handles chaning the mode to edit farmer
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/viewFarmer.tsx]: same typo

File: tsconfig.json [hunk 8]
```diff
@@ -27,8 +27,8 @@
     // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
 
     /* Additional Checks */
-    "noUnusedLocals": true,                /* Report errors on unused locals. */
-    "noUnusedParameters": true,            /* Report errors on unused parameters. */
+    "noUnusedLocals": false,                /* Report errors on unused locals. */
+    "noUnusedParameters": false,            /* Report errors on unused parameters. */
```
Comment (Right2Drive) [inline tsconfig.json]: Please leave this unchanged in your PR. It is perfectly fine to make this change for testing your local env, but we do want these to be enforced in master. Also I think the branch may be out of sync with the `clean` branch, might want to pull (we aren't using `noUnusedParameters`).

Comment (Right2Drive) [reply tsconfig.json]: You do indeed have conflicts with the base branch to deal with

File: src/view/pages/Farmer/tabs/Collect/index.tsx [hunk 9]
```diff
@@ -6,7 +6,7 @@ import CardSummary from '../../components/CardSummary';
 import ProductCard from '../../components/ProductCard';
 import createPage from '../../../../generators/Page/index';
 
-import styles from '../FarmerInformation/style';
+import { styles } from '../../styles';
```
[the remark this answers is not in the document]
Comment (mfalthaw) [reply src/view/pages/Farmer/tabs/Collect/index.tsx]: Changed `/src/view/pages/Farmer/styles.ts` to default export

File: src/view/pages/Farmer/tabs/Info/addFarmer.tsx [hunk 10]
```diff
@@ -1,17 +1,14 @@
 import * as React from 'react';
-import { Container, Header, H1, H2, H3, Content, Grid, Row, Col, Form, Item, Input, Label, Radio, Button, Right, ListItem, InputGroup, Picker }
```
[the remark this answers is not in the document]
Comment (mfalthaw) [reply src/view/pages/Farmer/tabs/Info/addFarmer.tsx]: You're right, I'm using `<Label />` in this page and hence; there's no need for H*.

File: src/view/pages/Farmer/tabs/Info/addFarmer.tsx [hunk 11]
```diff
@@ -27,12 +24,23 @@ export interface OwnProps {
 /**
```
[the remark this answers is not in the document]
Comment (mfalthaw) [reply src/view/pages/Farmer/tabs/Info/addFarmer.tsx]: Ok, this is the only thing giving me a headache. I took the function outside of the render. Here's the function outside of of the stateless component
```
const modeHandler = (props: OwnPropsType, page: string) => {
  props.modeHandler(page);
};
```

Here's how I'm calling it
```
onPress={() => modeHandler(props, 'view')}
```

And here's the error I'm getting
```
undefined is not a function (evaluating 'props.modeHandler(page)')
```

What do you think?

**Comment by mfalthaw** [comment]
Second time is the charm. Thanks @Right2Drive  :)

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 12]
```diff
@@ -0,0 +1,217 @@
...
+            </Row>
+            <Row style={styles.infoLabel}>
+              <Label>Notes</Label>
+            </Row>
+            <Row style={styles.infoLabel}>
+              <H2>{this.props.farmerNotes}</H2>
+            </Row>
+            <Row style={styles.editButton}>
+              <Col>
+                <Button block danger onPress={() => this.changeMode(modes.edit)}>
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: This is a bad practice, and I don't believe that it actually passes our linter. Whereas in your stateless component before it's hard to optimize because it doesn't have an instance to store functions on, this is not so for a `ComponentClass`. `onPress` should receive a premade function, so it's not being recreated every single time we rerender. An example of this would be:

```
private changeToEditMode = () => this.changeMode('edit')
```

Note that with the strictness on `mode` that this is enforced by types, because if you put in `edit1` it would be a compilation error.

File: src/view/pages/Farmer/tabs/Info/index.tsx [hunk 13]
```diff
@@ -0,0 +1,217 @@
...
+          <Grid>
+            <Row style={styles.infoLabel}>
+              <Col>
+                <Label>First Name</Label>
+                </Col>
+                <Col>
+                <Label>Last Name</Label>
+              </Col>
+            </Row>
+            <Row style={styles.input}>
```
Comment (Right2Drive) [inline src/view/pages/Farmer/tabs/Info/index.tsx]: See the following from Nick's branch:
```
  public render(): JSX.Element {
    return (
      <Content style={style.background} >
        <List
          dataArray={this.searchList()}
          renderRow={this.renderItem}
        />
      </Content>
    );
  }

  /** Function to render the individual list items */
  private renderItem(info: Farmer) {
    return (
      <ListItem
        key={info.id}
        onPress={this.onItemClick}
      >
        <View>
          <Text style={style.name}>
            {info.name}
          </Text>
          <Text style={style.phone}>
            Phone: {info.phoneNumber}
          </Text>
        </View>
      </ListItem>
    );
```

He calls a function on an array of data that specifies how to render each entry of the data. This is not the way you would typically do it however, as most elements do not specifically have a `renderRow` prop or anything similar. Typically this would be done via the following:
```
public render(): JSX.Element {
    return (
      <Content style={style.background} >
        <List>
          {this.searchList().map(this.renderItem)}
        </List>
      </Content>
    );
  }
```

Which is the same thing Nick did, which is why I'm not sure why `native-base` even provides a different API when you can do it with React itself. I would recommend trying to adopt a similar pattern to reduce repeated code if possible

File: tsconfig.json [hunk 14]
```diff
@@ -27,7 +27,7 @@
     // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
 
     /* Additional Checks */
-    "noUnusedLocals": true                /* Report errors on unused locals. */
+    "noUnusedLocals": true,                /* Report errors on unused locals. */
```
Comment (Right2Drive) [inline tsconfig.json]: I think this has indeed diverged from the base branch, because `,` in json is not actually part of the spec, and merely something allowed by typescript for some reason. If you were to open this file in sublime it would likely complain about syntax errors

File: src/view/pages/Farmer/tabs/Info/addFarmer.tsx [hunk 15]
```diff
@@ -25,14 +22,25 @@ export interface OwnProps {
...
+  // page === 'view' ? props.modeHandler(page) : false;
+  props.modeHandler(page);
+};
+
+const updatePaymentCycle = (props: OwnPropsType, value: string) => {
+  props.selectedPaymentCycle = value;
+};
+
+const updatePaymentMethod = (props: OwnPropsType, value: string) => {
+  props.selectedPaymentMethod = value;
```
[the remark this answers is not in the document]
Comment (mfalthaw) [reply src/view/pages/Farmer/tabs/Info/addFarmer.tsx]: Ahh do you think it's just better to make this a `stateful` component? I'm having trouble making these functions work this way :p

File: src/view/pages/Farmer/tabs/Info/index.tsx (hunk 13 above)
Comment (mfalthaw) [reply src/view/pages/Farmer/tabs/Info/index.tsx]: This is very interesting, and I totally see your point. This reduces copied code and is much cleaner. However, I'll open an issue for this to go back and do it later since we have to prioritize other things in the time being. Thanks for the insight!

**Comment by mfalthaw** [comment]
@Right2Drive Round 3. I did the best I could to cleanup more, some things make a little more sense now. Thanks again!

File: src/view/pages/Farmer/tabs/Info/index.tsx (hunk 13 above)
Comment (jeinglis) [reply src/view/pages/Farmer/tabs/Info/index.tsx]: That's good to know. Thanks for pointing it out brad.
